version: "3.7"

services:
  linqpal-app:
    container_name: linqpal-app
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
        - linqpal-backend:linqpal-backend
    ports:
      - 8080:80
      - 44443:443
    networks:
    - all_containers_databases_portal-databases-network

networks:
  all_containers_databases_portal-databases-network:
    external: true