version: "3.7"

services:
  linqpal-mongodb:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: DockerfileMongo
    container_name: "linqpal-mongodb"
    volumes:
      - linqpal-mongo-data:/data/db
    ports:
      - 27117:27017
    env_file:
      - ./mongo.env
    networks:
      - portal-databases-network

volumes:
  portal-mongo-data: {}

networks:
  portal-databases-network:
    driver: bridge